/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WirelessPresentationRouteImport } from './routes/wireless-presentation'
import { Route as ThemePreviewRouteImport } from './routes/theme-preview'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProjectorRouteImport } from './routes/projector'
import { Route as ProductLineRouteImport } from './routes/product-line'
import { Route as LedDisplayRouteImport } from './routes/led-display'
import { Route as InteractiveDisplayRouteImport } from './routes/interactive-display'
import { Route as ContactusRouteImport } from './routes/contactus'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as AvSolutionsRouteImport } from './routes/av-solutions'
import { Route as AboutusRouteImport } from './routes/aboutus'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as IndustrySlugRouteImport } from './routes/industry.$slug'
import { Route as CategoryIdRouteImport } from './routes/category.$id'
import { Route as BrandsSlugRouteImport } from './routes/brands.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as ApiPublicChatbotRouteImport } from './routes/api/public/chatbot'
import { Route as ApiAdminUploadRouteImport } from './routes/api/admin/upload'
import { Route as ApiAdminContentRouteImport } from './routes/api/admin/content'

const WirelessPresentationRoute = WirelessPresentationRouteImport.update({
  id: '/wireless-presentation',
  path: '/wireless-presentation',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemePreviewRoute = ThemePreviewRouteImport.update({
  id: '/theme-preview',
  path: '/theme-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectorRoute = ProjectorRouteImport.update({
  id: '/projector',
  path: '/projector',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductLineRoute = ProductLineRouteImport.update({
  id: '/product-line',
  path: '/product-line',
  getParentRoute: () => rootRouteImport,
} as any)
const LedDisplayRoute = LedDisplayRouteImport.update({
  id: '/led-display',
  path: '/led-display',
  getParentRoute: () => rootRouteImport,
} as any)
const InteractiveDisplayRoute = InteractiveDisplayRouteImport.update({
  id: '/interactive-display',
  path: '/interactive-display',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactusRoute = ContactusRouteImport.update({
  id: '/contactus',
  path: '/contactus',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const AvSolutionsRoute = AvSolutionsRouteImport.update({
  id: '/av-solutions',
  path: '/av-solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutusRoute = AboutusRouteImport.update({
  id: '/aboutus',
  path: '/aboutus',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustrySlugRoute = IndustrySlugRouteImport.update({
  id: '/industry/$slug',
  path: '/industry/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryIdRoute = CategoryIdRouteImport.update({
  id: '/category/$id',
  path: '/category/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsSlugRoute = BrandsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BrandsRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatbotRoute = ApiPublicChatbotRouteImport.update({
  id: '/api/public/chatbot',
  path: '/api/public/chatbot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUploadRoute = ApiAdminUploadRouteImport.update({
  id: '/api/admin/upload',
  path: '/api/admin/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminContentRoute = ApiAdminContentRouteImport.update({
  id: '/api/admin/content',
  path: '/api/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aboutus': typeof AboutusRoute
  '/av-solutions': typeof AvSolutionsRoute
  '/brands': typeof BrandsRouteWithChildren
  '/contactus': typeof ContactusRoute
  '/interactive-display': typeof InteractiveDisplayRoute
  '/led-display': typeof LedDisplayRoute
  '/product-line': typeof ProductLineRoute
  '/projector': typeof ProjectorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRoute
  '/theme-preview': typeof ThemePreviewRoute
  '/wireless-presentation': typeof WirelessPresentationRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/category/$id': typeof CategoryIdRoute
  '/industry/$slug': typeof IndustrySlugRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/api/admin/content': typeof ApiAdminContentRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
  '/api/public/chatbot': typeof ApiPublicChatbotRoute
  '/api/public/contact': typeof ApiPublicContactRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aboutus': typeof AboutusRoute
  '/av-solutions': typeof AvSolutionsRoute
  '/brands': typeof BrandsRouteWithChildren
  '/contactus': typeof ContactusRoute
  '/interactive-display': typeof InteractiveDisplayRoute
  '/led-display': typeof LedDisplayRoute
  '/product-line': typeof ProductLineRoute
  '/projector': typeof ProjectorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRoute
  '/theme-preview': typeof ThemePreviewRoute
  '/wireless-presentation': typeof WirelessPresentationRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/category/$id': typeof CategoryIdRoute
  '/industry/$slug': typeof IndustrySlugRoute
  '/product/$id': typeof ProductIdRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/api/admin/content': typeof ApiAdminContentRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
  '/api/public/chatbot': typeof ApiPublicChatbotRoute
  '/api/public/contact': typeof ApiPublicContactRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aboutus': typeof AboutusRoute
  '/av-solutions': typeof AvSolutionsRoute
  '/brands': typeof BrandsRouteWithChildren
  '/contactus': typeof ContactusRoute
  '/interactive-display': typeof InteractiveDisplayRoute
  '/led-display': typeof LedDisplayRoute
  '/product-line': typeof ProductLineRoute
  '/projector': typeof ProjectorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRoute
  '/theme-preview': typeof ThemePreviewRoute
  '/wireless-presentation': typeof WirelessPresentationRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/category/$id': typeof CategoryIdRoute
  '/industry/$slug': typeof IndustrySlugRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/api/admin/content': typeof ApiAdminContentRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
  '/api/public/chatbot': typeof ApiPublicChatbotRoute
  '/api/public/contact': typeof ApiPublicContactRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aboutus'
    | '/av-solutions'
    | '/brands'
    | '/contactus'
    | '/interactive-display'
    | '/led-display'
    | '/product-line'
    | '/projector'
    | '/sitemap.xml'
    | '/solutions'
    | '/theme-preview'
    | '/wireless-presentation'
    | '/blog/$slug'
    | '/brands/$slug'
    | '/category/$id'
    | '/industry/$slug'
    | '/product/$id'
    | '/admin/'
    | '/blog/'
    | '/api/admin/content'
    | '/api/admin/upload'
    | '/api/public/chatbot'
    | '/api/public/contact'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aboutus'
    | '/av-solutions'
    | '/brands'
    | '/contactus'
    | '/interactive-display'
    | '/led-display'
    | '/product-line'
    | '/projector'
    | '/sitemap.xml'
    | '/solutions'
    | '/theme-preview'
    | '/wireless-presentation'
    | '/blog/$slug'
    | '/brands/$slug'
    | '/category/$id'
    | '/industry/$slug'
    | '/product/$id'
    | '/admin'
    | '/blog'
    | '/api/admin/content'
    | '/api/admin/upload'
    | '/api/public/chatbot'
    | '/api/public/contact'
  id:
    | '__root__'
    | '/'
    | '/aboutus'
    | '/av-solutions'
    | '/brands'
    | '/contactus'
    | '/interactive-display'
    | '/led-display'
    | '/product-line'
    | '/projector'
    | '/sitemap.xml'
    | '/solutions'
    | '/theme-preview'
    | '/wireless-presentation'
    | '/blog/$slug'
    | '/brands/$slug'
    | '/category/$id'
    | '/industry/$slug'
    | '/product/$id'
    | '/admin/'
    | '/blog/'
    | '/api/admin/content'
    | '/api/admin/upload'
    | '/api/public/chatbot'
    | '/api/public/contact'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutusRoute: typeof AboutusRoute
  AvSolutionsRoute: typeof AvSolutionsRoute
  BrandsRoute: typeof BrandsRouteWithChildren
  ContactusRoute: typeof ContactusRoute
  InteractiveDisplayRoute: typeof InteractiveDisplayRoute
  LedDisplayRoute: typeof LedDisplayRoute
  ProductLineRoute: typeof ProductLineRoute
  ProjectorRoute: typeof ProjectorRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolutionsRoute: typeof SolutionsRoute
  ThemePreviewRoute: typeof ThemePreviewRoute
  WirelessPresentationRoute: typeof WirelessPresentationRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CategoryIdRoute: typeof CategoryIdRoute
  IndustrySlugRoute: typeof IndustrySlugRoute
  ProductIdRoute: typeof ProductIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiAdminContentRoute: typeof ApiAdminContentRoute
  ApiAdminUploadRoute: typeof ApiAdminUploadRoute
  ApiPublicChatbotRoute: typeof ApiPublicChatbotRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wireless-presentation': {
      id: '/wireless-presentation'
      path: '/wireless-presentation'
      fullPath: '/wireless-presentation'
      preLoaderRoute: typeof WirelessPresentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theme-preview': {
      id: '/theme-preview'
      path: '/theme-preview'
      fullPath: '/theme-preview'
      preLoaderRoute: typeof ThemePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projector': {
      id: '/projector'
      path: '/projector'
      fullPath: '/projector'
      preLoaderRoute: typeof ProjectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-line': {
      id: '/product-line'
      path: '/product-line'
      fullPath: '/product-line'
      preLoaderRoute: typeof ProductLineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/led-display': {
      id: '/led-display'
      path: '/led-display'
      fullPath: '/led-display'
      preLoaderRoute: typeof LedDisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interactive-display': {
      id: '/interactive-display'
      path: '/interactive-display'
      fullPath: '/interactive-display'
      preLoaderRoute: typeof InteractiveDisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactus': {
      id: '/contactus'
      path: '/contactus'
      fullPath: '/contactus'
      preLoaderRoute: typeof ContactusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/av-solutions': {
      id: '/av-solutions'
      path: '/av-solutions'
      fullPath: '/av-solutions'
      preLoaderRoute: typeof AvSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aboutus': {
      id: '/aboutus'
      path: '/aboutus'
      fullPath: '/aboutus'
      preLoaderRoute: typeof AboutusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry/$slug': {
      id: '/industry/$slug'
      path: '/industry/$slug'
      fullPath: '/industry/$slug'
      preLoaderRoute: typeof IndustrySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$id': {
      id: '/category/$id'
      path: '/category/$id'
      fullPath: '/category/$id'
      preLoaderRoute: typeof CategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$slug': {
      id: '/brands/$slug'
      path: '/$slug'
      fullPath: '/brands/$slug'
      preLoaderRoute: typeof BrandsSlugRouteImport
      parentRoute: typeof BrandsRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chatbot': {
      id: '/api/public/chatbot'
      path: '/api/public/chatbot'
      fullPath: '/api/public/chatbot'
      preLoaderRoute: typeof ApiPublicChatbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/upload': {
      id: '/api/admin/upload'
      path: '/api/admin/upload'
      fullPath: '/api/admin/upload'
      preLoaderRoute: typeof ApiAdminUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/content': {
      id: '/api/admin/content'
      path: '/api/admin/content'
      fullPath: '/api/admin/content'
      preLoaderRoute: typeof ApiAdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BrandsRouteChildren {
  BrandsSlugRoute: typeof BrandsSlugRoute
}

const BrandsRouteChildren: BrandsRouteChildren = {
  BrandsSlugRoute: BrandsSlugRoute,
}

const BrandsRouteWithChildren =
  BrandsRoute._addFileChildren(BrandsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutusRoute: AboutusRoute,
  AvSolutionsRoute: AvSolutionsRoute,
  BrandsRoute: BrandsRouteWithChildren,
  ContactusRoute: ContactusRoute,
  InteractiveDisplayRoute: InteractiveDisplayRoute,
  LedDisplayRoute: LedDisplayRoute,
  ProductLineRoute: ProductLineRoute,
  ProjectorRoute: ProjectorRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolutionsRoute: SolutionsRoute,
  ThemePreviewRoute: ThemePreviewRoute,
  WirelessPresentationRoute: WirelessPresentationRoute,
  BlogSlugRoute: BlogSlugRoute,
  CategoryIdRoute: CategoryIdRoute,
  IndustrySlugRoute: IndustrySlugRoute,
  ProductIdRoute: ProductIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiAdminContentRoute: ApiAdminContentRoute,
  ApiAdminUploadRoute: ApiAdminUploadRoute,
  ApiPublicChatbotRoute: ApiPublicChatbotRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
